# Render Blueprint �? Shwe Yee POS (free tier)
services:
  - type: web
    name: shweyee-pos
    runtime: docker
    plan: free
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: "Shwe Yee POS"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false            # Render dashboard တွ�?် ကိုယ်တို�?်ထည့်ရန်
      - key: APP_LOCALE
        value: my
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: gateway01.ap-southeast-1.prod.aws.tidbcloud.com            # TiDB Cloud host
      - key: DB_PORT
        value: "4000"
      - key: DB_DATABASE
        sync: shweyee_pos
      - key: DB_USERNAME
        sync: M2bsnxJvesdZa2p.root
      - key: DB_PASSWORD
        sync: jMglz0rOKAhlm7sN
      - key: MYSQL_ATTR_SSL_CA
        value: /etc/ssl/certs/ca-certificates.crt   # TiDB TLS
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_SECURE_COOKIE
        value: "true"
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: SEED_ON_DEPLOY
        value: "true"          # ပထ�? deploy ပြီးလျှ�?် false ပြန်ပြော�?်းပါ
